### ISSUE TITLE
wholeword argument not working with kwic

### ISSUE THREAD

**Issue by mmagana7** [kbenoit/ME414#2]
Hi Ken,

I was playing with the _kwic_ command and found out that the _wholeword_ argument is not working anymore. 

i.e 
`require(quanteda)`
`kwic(ie2010Corpus, "euro", wholeword=TRUE)`

returns the warning message below
**Warning message:
In tokenize.character(x, ...) : Argument wholeword not used.**

Regards
Manuel

**Comment by kbenoit** [comment]
That's right, it's not working because it was removed. New syntax is to specify one of `valuetype`, where the same behaviour as `wholeword = TRUE` is the default. This happens because the the default `valuetype = "glob"` and `"euro"` with no wild-card characters will only match the whole word.

Contrast this with `valuetype = "regex"` where the `"euro"` is a pattern match without the restrictions of being the start or end of a pattern, since that is how regular expressions work.

```{r}
> nrow(kwic(ie2010Corpus, "euro"))
[1] 12
> nrow(kwic(ie2010Corpus, "euro", valuetype = "regex"))
[1] 41
```
